//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace easySave___Graphic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("easySave___Graphic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action is irreversible.
        /// </summary>
        public static string advertisement {
            get {
                return ResourceManager.GetString("advertisement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string apply {
            get {
                return ResourceManager.GetString("apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of the process (if not in use).
        /// </summary>
        public static string chooseProcess {
            get {
                return ResourceManager.GetString("chooseProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string complete {
            get {
                return ResourceManager.GetString("complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This setting will prevent the program to run if a specific process is in use.
        /// </summary>
        public static string descSettingsBS {
            get {
                return ResourceManager.GetString("descSettingsBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination path.
        /// </summary>
        public static string destination {
            get {
                return ResourceManager.GetString("destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error ! Incorrect destination path : .
        /// </summary>
        public static string destPathError {
            get {
                return ResourceManager.GetString("destPathError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Differential.
        /// </summary>
        public static string differential {
            get {
                return ResourceManager.GetString("differential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption.
        /// </summary>
        public static string encryptionMenu {
            get {
                return ResourceManager.GetString("encryptionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop copying because the business software is running.
        /// </summary>
        public static string errorProcessRunning {
            get {
                return ResourceManager.GetString("errorProcessRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter file extension (if not in the list).
        /// </summary>
        public static string fileExtension {
            get {
                return ResourceManager.GetString("fileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log file format.
        /// </summary>
        public static string formatLog {
            get {
                return ResourceManager.GetString("formatLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string fr {
            get {
                return ResourceManager.GetString("fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string french {
            get {
                return ResourceManager.GetString("french", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of current processes.
        /// </summary>
        public static string listProcess {
            get {
                return ResourceManager.GetString("listProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make your choice : .
        /// </summary>
        public static string makeChoice {
            get {
                return ResourceManager.GetString("makeChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. simultaneous 
        ///files size.
        /// </summary>
        public static string maxSize {
            get {
                return ResourceManager.GetString("maxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible to run backups because the business software is running.
        /// </summary>
        public static string noLaunchSave {
            get {
                return ResourceManager.GetString("noLaunchSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No job selected in the main menu.
        /// </summary>
        public static string noSelectJob {
            get {
                return ResourceManager.GetString("noSelectJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string other {
            get {
                return ResourceManager.GetString("other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prioritization.
        /// </summary>
        public static string prioritization {
            get {
                return ResourceManager.GetString("prioritization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string progress {
            get {
                return ResourceManager.GetString("progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Software.
        /// </summary>
        public static string proSoftware {
            get {
                return ResourceManager.GetString("proSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string remove {
            get {
                return ResourceManager.GetString("remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string replay {
            get {
                return ResourceManager.GetString("replay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save all jobs.
        /// </summary>
        public static string saveAllJobs {
            get {
                return ResourceManager.GetString("saveAllJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save menu.
        /// </summary>
        public static string saveMenu {
            get {
                return ResourceManager.GetString("saveMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving the job : .
        /// </summary>
        public static string saveOneJob {
            get {
                return ResourceManager.GetString("saveOneJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write the extension to add!.
        /// </summary>
        public static string selectAddExtension {
            get {
                return ResourceManager.GetString("selectAddExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an extension to remove!.
        /// </summary>
        public static string selectExtension {
            get {
                return ResourceManager.GetString("selectExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a job.
        /// </summary>
        public static string selectJob {
            get {
                return ResourceManager.GetString("selectJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string setting {
            get {
                return ResourceManager.GetString("setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source path.
        /// </summary>
        public static string source {
            get {
                return ResourceManager.GetString("source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error ! Incorrect source path : .
        /// </summary>
        public static string sourcePathError {
            get {
                return ResourceManager.GetString("sourcePathError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup type.
        /// </summary>
        public static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose file extension.
        /// </summary>
        public static string typeExtension {
            get {
                return ResourceManager.GetString("typeExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for big files to copy.
        /// </summary>
        public static string waitForBigFiles {
            get {
                return ResourceManager.GetString("waitForBigFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this job : .
        /// </summary>
        public static string wantDelete {
            get {
                return ResourceManager.GetString("wantDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application language.
        /// </summary>
        public static string WindowLangTitle {
            get {
                return ResourceManager.GetString("WindowLangTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
